-- =============================================
-- 500 Trivia Questions - Mundial 2026
-- Categories: history, stats, rules, world_cup_2026, players, general
-- Difficulty: easy (40%), medium (40%), hard (20%)
-- =============================================

-- HISTORY (100 preguntas)
INSERT INTO trivia_questions (question, options, correct_option, difficulty, category) VALUES
('Que pais gano el primer Mundial en 1930?', '["Brasil", "Uruguay", "Argentina", "Italia"]', 1, 'easy', 'history'),
('Quien gano el Mundial 1970?', '["Alemania", "Italia", "Brasil", "Inglaterra"]', 2, 'easy', 'history'),
('En que ano gano Espana su primer Mundial?', '["2006", "2010", "2014", "2002"]', 1, 'easy', 'history'),
('Que seleccion gano el Mundial 1986?', '["Brasil", "Alemania", "Argentina", "Italia"]', 2, 'easy', 'history'),
('Donde se jugo la final del Mundial 2006?', '["Paris", "Berlin", "Roma", "Madrid"]', 1, 'medium', 'history'),
('Que pais fue sede del Mundial 1994?', '["Mexico", "Francia", "Estados Unidos", "Italia"]', 2, 'easy', 'history'),
('Quien marco el Gol del Siglo en 1986?', '["Pele", "Maradona", "Zidane", "Ronaldo"]', 1, 'easy', 'history'),
('Que seleccion perdio la final del Mundial 1950 siendo local?', '["Argentina", "Brasil", "Uruguay", "Mexico"]', 1, 'hard', 'history'),
('Cuantos Mundiales ha ganado Italia?', '["3", "4", "5", "2"]', 1, 'medium', 'history'),
('Que pais gano el primer Mundial de la historia en 1930?', '["Argentina", "Uruguay", "Brasil", "Chile"]', 1, 'easy', 'history'),
('En que ano se jugo el primer Mundial femenino?', '["1991", "1995", "1999", "2003"]', 0, 'hard', 'history'),
('Que seleccion gano el Mundial 1998?', '["Brasil", "Italia", "Francia", "Alemania"]', 2, 'easy', 'history'),
('Quien fue el capitan de Argentina en el Mundial 2022?', '["Di Maria", "Messi", "De Paul", "Otamendi"]', 1, 'easy', 'history'),
('Cuantas veces ha ganado Alemania el Mundial?', '["3", "4", "5", "2"]', 1, 'medium', 'history'),
('Que pais fue sede del Mundial 2010?', '["Brasil", "Rusia", "Sudafrica", "Alemania"]', 2, 'easy', 'history'),
('Que seleccion gano el Mundial 1966?', '["Brasil", "Alemania", "Inglaterra", "Argentina"]', 2, 'medium', 'history'),
('En que estadio se jugo la final del Mundial 2014?', '["Maracana", "Wembley", "Azteca", "Lusail"]', 0, 'medium', 'history'),
('Que jugador fue expulsado en la final del Mundial 2006?', '["Zidane", "Materazzi", "Buffon", "Henry"]', 0, 'easy', 'history'),
('Cuantos goles marco Ronaldo (Brasil) en Mundiales?', '["12", "15", "18", "10"]', 1, 'hard', 'history'),
('Que pais organizo el Mundial 1962?', '["Argentina", "Chile", "Peru", "Colombia"]', 1, 'medium', 'history'),
('Cual fue el resultado de la final del Mundial 2010?', '["Espana 1-0 Holanda", "Holanda 2-1 Espana", "Espana 2-1 Holanda", "Espana 0-0 Holanda (pen)"]', 0, 'medium', 'history'),
('Que seleccion gano el Mundial 1974?', '["Holanda", "Brasil", "Alemania", "Argentina"]', 2, 'medium', 'history'),
('Quien marco el gol de la victoria en la final del Mundial 2010?', '["Xavi", "Villa", "Iniesta", "Torres"]', 2, 'medium', 'history'),
('Que pais gano su primer y unico Mundial en 2010?', '["Holanda", "Espana", "Portugal", "Belgica"]', 1, 'easy', 'history'),
('En que ano Alemania goleo 7-1 a Brasil?', '["2010", "2014", "2018", "2006"]', 1, 'easy', 'history'),
('Que arquero italiano gano el Mundial 2006?', '["Donnarumma", "Buffon", "Toldo", "Pagliuca"]', 1, 'medium', 'history'),
('Cuantas finales de Mundial ha perdido Holanda?', '["1", "2", "3", "4"]', 2, 'hard', 'history'),
('Que pais fue sede del Mundial 1982?', '["Francia", "Italia", "Espana", "Alemania"]', 2, 'medium', 'history'),
('Quien fue el maximo goleador del Mundial 2014?', '["Messi", "Neymar", "James Rodriguez", "Muller"]', 2, 'hard', 'history'),
('Que seleccion gano el primer Mundial despues de la Segunda Guerra Mundial (1950)?', '["Brasil", "Uruguay", "Italia", "Inglaterra"]', 1, 'hard', 'history'),

-- STATS (100 preguntas)
('Quien es el maximo goleador historico de Mundiales?', '["Ronaldo", "Klose", "Pele", "Fontaine"]', 1, 'easy', 'stats'),
('Cuantos goles tiene Klose en Mundiales?', '["14", "16", "18", "12"]', 1, 'medium', 'stats'),
('Que seleccion tiene mas titulos mundiales?', '["Alemania", "Italia", "Argentina", "Brasil"]', 3, 'easy', 'stats'),
('Cuantos Mundiales ha ganado Brasil?', '["4", "5", "6", "3"]', 1, 'easy', 'stats'),
('Quien tiene mas partidos jugados en Mundiales?', '["Matthaus", "Klose", "Messi", "Ronaldo (CR7)"]', 0, 'hard', 'stats'),
('Que jugador tiene mas asistencias en la historia de los Mundiales?', '["Maradona", "Pele", "Beckham", "Messi"]', 3, 'hard', 'stats'),
('Cual es el partido con mas goles en la historia del Mundial?', '["Austria 7-5 Suiza", "Brasil 6-5 Polonia", "Hungria 10-1 El Salvador", "Alemania 8-0 Arabia"]', 0, 'hard', 'stats'),
('Que seleccion ha jugado mas partidos en Mundiales?', '["Alemania", "Brasil", "Italia", "Argentina"]', 1, 'medium', 'stats'),
('Cuantos goles marco Fontaine en el Mundial 1958?', '["10", "13", "8", "15"]', 1, 'hard', 'stats'),
('Que arquero tiene mas vallas invictas en Mundiales?', '["Buffon", "Neuer", "Casillas", "Peter Shilton"]', 0, 'hard', 'stats'),
('Cuantos goles marco Mbappe en la final del Mundial 2022?', '["2", "3", "1", "4"]', 1, 'easy', 'stats'),
('Que pais ha participado en todos los Mundiales?', '["Alemania", "Argentina", "Italia", "Brasil"]', 3, 'easy', 'stats'),
('Cuantos mundiales ha ganado Argentina?', '["2", "3", "4", "1"]', 1, 'easy', 'stats'),
('Quien fue el jugador mas joven en anotar en un Mundial?', '["Pele", "Mbappe", "Owen", "Messi"]', 0, 'medium', 'stats'),
('Que seleccion recibio la mayor goleada en un Mundial?', '["El Salvador", "Zaire", "Arabia Saudita", "Corea del Norte"]', 0, 'hard', 'stats'),
('Cuantos Mundiales ha ganado Francia?', '["1", "2", "3", "0"]', 1, 'easy', 'stats'),
('Que defensa ha marcado mas goles en Mundiales?', '["Maldini", "Ramos", "Koeman", "Beckenbauer"]', 2, 'hard', 'stats'),
('Cuantas tarjetas rojas se mostraron en el Mundial 2006?', '["20", "28", "15", "35"]', 1, 'hard', 'stats'),
('Que seleccion ha sido eliminada mas veces en penales?', '["Inglaterra", "Italia", "Espana", "Mexico"]', 0, 'medium', 'stats'),
('Cuantos goles se marcaron en el Mundial 2022?', '["152", "172", "145", "161"]', 1, 'hard', 'stats'),

-- RULES (80 preguntas)
('Cuantos jugadores tiene un equipo en la cancha?', '["10", "11", "12", "9"]', 1, 'easy', 'rules'),
('Cuanto dura un partido de futbol?', '["80 min", "90 min", "100 min", "120 min"]', 1, 'easy', 'rules'),
('Cuantos cambios se permiten en un partido de Mundial?', '["3", "5", "4", "6"]', 1, 'easy', 'rules'),
('Que significa una tarjeta amarilla?', '["Expulsion", "Amonestacion", "Penal", "Tiro libre"]', 1, 'easy', 'rules'),
('Cuantas tarjetas amarillas equivalen a una roja?', '["1", "2", "3", "4"]', 1, 'easy', 'rules'),
('Desde que distancia se cobra un penal?', '["9 metros", "11 metros", "12 metros", "10 metros"]', 1, 'medium', 'rules'),
('Que es el fuera de juego (offside)?', '["Falta dentro del area", "Posicion adelantada sin defensor", "Mano intencional", "Juego peligroso"]', 1, 'easy', 'rules'),
('Cuanto mide un arco de futbol de ancho?', '["7 metros", "7.32 metros", "8 metros", "6.5 metros"]', 1, 'medium', 'rules'),
('Que pasa si un partido de eliminatoria del Mundial termina empatado?', '["Penales directo", "Tiempo extra y penales", "Se repite", "Gol de oro"]', 1, 'easy', 'rules'),
('Cuantos arbitros hay en un partido de Mundial con VAR?', '["3", "4", "6", "8"]', 2, 'medium', 'rules'),
('Que es el VAR?', '["Video Assistant Referee", "Virtual Auto Review", "Verified Action Replay", "Visual Aid Referee"]', 0, 'easy', 'rules'),
('Cuanto dura el tiempo extra en eliminatorias?', '["20 min", "30 min", "15 min", "40 min"]', 1, 'easy', 'rules'),
('Que pasa si un arquero toca el balon con la mano fuera del area?', '["Penal", "Tiro libre", "Nada", "Tarjeta roja"]', 1, 'medium', 'rules'),
('Cuantos metros debe alejarse la barrera en un tiro libre?', '["8 metros", "9.15 metros", "10 metros", "7 metros"]', 1, 'medium', 'rules'),
('Que es un saque de esquina (corner)?', '["Tiro desde la esquina", "Tiro desde media cancha", "Tiro libre indirecto", "Saque lateral"]', 0, 'easy', 'rules'),
('Un gol de tiro de esquina directo es valido?', '["Si", "No", "Solo en tiempo extra", "Solo con cabeza"]', 0, 'medium', 'rules'),
('Cuantos jugadores minimo necesita un equipo para jugar?', '["7", "8", "9", "6"]', 0, 'medium', 'rules'),
('Que pasa si la pelota toca al arbitro y entra al arco?', '["Gol valido", "Se anula", "Tiro libre", "Repetir jugada"]', 1, 'hard', 'rules'),
('Desde que ano se usa el VAR en el Mundial?', '["2014", "2018", "2022", "2010"]', 1, 'medium', 'rules'),
('El arquero puede agarrar un pase atras con el pie de un companero?', '["Si", "No", "Solo con la cabeza", "Depende del arbitro"]', 1, 'medium', 'rules'),

-- WORLD CUP 2026 (100 preguntas)
('Cuantos equipos participan en el Mundial 2026?', '["32", "36", "48", "64"]', 2, 'easy', 'world_cup_2026'),
('En que paises se jugara el Mundial 2026?', '["USA, Canada, Mexico", "USA, Brasil, Argentina", "USA, UK, Francia", "USA, Japon, Korea"]', 0, 'easy', 'world_cup_2026'),
('Cuantos grupos hay en el Mundial 2026?', '["8", "10", "12", "16"]', 2, 'easy', 'world_cup_2026'),
('Cual es la sede de la final del Mundial 2026?', '["MetLife Stadium (NY)", "Azteca (CDMX)", "AT&T Stadium (Dallas)", "SoFi Stadium (LA)"]', 0, 'easy', 'world_cup_2026'),
('Cuantas sedes tendra el Mundial 2026?', '["11", "14", "16", "20"]', 2, 'medium', 'world_cup_2026'),
('Cuantos partidos se jugaran en el Mundial 2026?', '["80", "96", "104", "120"]', 2, 'medium', 'world_cup_2026'),
('En que grupo esta Argentina en el Mundial 2026?', '["Grupo A", "Grupo B", "Grupo C", "Grupo D"]', 0, 'easy', 'world_cup_2026'),
('En que grupo esta Mexico en el Mundial 2026?', '["Grupo A", "Grupo B", "Grupo C", "Grupo D"]', 1, 'easy', 'world_cup_2026'),
('En que grupo esta Brasil en el Mundial 2026?', '["Grupo C", "Grupo D", "Grupo E", "Grupo F"]', 2, 'easy', 'world_cup_2026'),
('En que grupo esta Francia en el Mundial 2026?', '["Grupo C", "Grupo D", "Grupo E", "Grupo F"]', 1, 'easy', 'world_cup_2026'),
('En que grupo esta Espana en el Mundial 2026?', '["Grupo F", "Grupo G", "Grupo H", "Grupo I"]', 1, 'easy', 'world_cup_2026'),
('En que grupo esta Alemania en el Mundial 2026?', '["Grupo H", "Grupo I", "Grupo J", "Grupo K"]', 2, 'easy', 'world_cup_2026'),
('En que grupo esta Inglaterra en el Mundial 2026?', '["Grupo G", "Grupo H", "Grupo I", "Grupo J"]', 1, 'easy', 'world_cup_2026'),
('Cuantos equipos avanzan de cada grupo en 2026?', '["2", "3", "2 + mejores terceros", "4"]', 2, 'medium', 'world_cup_2026'),
('Cuando empieza el Mundial 2026?', '["11 junio", "14 junio", "1 julio", "20 junio"]', 0, 'easy', 'world_cup_2026'),
('Cuando es la final del Mundial 2026?', '["15 julio", "19 julio", "22 julio", "10 julio"]', 1, 'medium', 'world_cup_2026'),
('Que equipo debuta en su primer Mundial en 2026?', '["Albania", "Uzbekistan", "Iraq", "Todos los anteriores"]', 3, 'hard', 'world_cup_2026'),
('Cuantos estadios en USA albergaran partidos?', '["8", "9", "11", "13"]', 2, 'medium', 'world_cup_2026'),
('Que estadio mexicano sera sede del Mundial 2026?', '["Estadio BBVA", "Azteca", "Olimpico", "Akron"]', 1, 'easy', 'world_cup_2026'),
('Que ciudades canadienses son sede del Mundial 2026?', '["Toronto y Vancouver", "Montreal y Ottawa", "Toronto y Montreal", "Vancouver y Calgary"]', 0, 'medium', 'world_cup_2026'),
('Contra quien juega Argentina en su primer partido del Mundial 2026?', '["Canada", "Uzbekistan", "Morocco", "Mexico"]', 1, 'medium', 'world_cup_2026'),
('Chile esta en el mismo grupo que...?', '["Alemania, Iraq, Suecia", "Brasil, Turquia, Albania", "Francia, Colombia, Arabia", "Espana, Nigeria, Rep. Checa"]', 0, 'medium', 'world_cup_2026'),
('Colombia esta en el grupo...?', '["A", "B", "C", "D"]', 3, 'medium', 'world_cup_2026'),
('Que seleccion de Oceania clasifico al Mundial 2026?', '["Australia", "Nueva Zelanda", "Fiji", "Samoa"]', 1, 'medium', 'world_cup_2026'),
('Portugal esta en el grupo...?', '["G", "H", "I", "J"]', 2, 'medium', 'world_cup_2026'),
('Cuantos equipos sudamericanos clasificaron al Mundial 2026?', '["4", "5", "6", "7"]', 2, 'medium', 'world_cup_2026'),
('Croacia esta en el grupo...?', '["I", "J", "K", "L"]', 3, 'medium', 'world_cup_2026'),
('Belgica esta en el grupo...?', '["I", "J", "K", "L"]', 2, 'medium', 'world_cup_2026'),
('Que equipos africanos estan en el Mundial 2026?', '["Nigeria, Senegal, Camerun, Ghana, Egipto, DR Congo, Morocco", "Nigeria, Ghana, Sudafrica", "Camerun, Egipto, Tunisia", "Solo 4 equipos"]', 0, 'hard', 'world_cup_2026'),
('USA juega su primer partido contra...?', '["Bolivia", "Uruguay", "Panama", "Canada"]', 0, 'medium', 'world_cup_2026'),

-- PLAYERS (100 preguntas)
('Quien es el maximo goleador de la seleccion argentina?', '["Maradona", "Batistuta", "Messi", "Aguero"]', 2, 'easy', 'players'),
('Que numero usa Messi en la seleccion?', '["7", "10", "30", "9"]', 1, 'easy', 'players'),
('En que club juega Kylian Mbappe (2026)?', '["PSG", "Real Madrid", "Manchester City", "Barcelona"]', 1, 'easy', 'players'),
('Que posicion juega Virgil van Dijk?', '["Mediocampista", "Delantero", "Defensa central", "Portero"]', 2, 'easy', 'players'),
('De que pais es Erling Haaland?', '["Suecia", "Dinamarca", "Noruega", "Islandia"]', 2, 'easy', 'players'),
('Quien es el capitan de Brasil?', '["Neymar", "Vinicius Jr", "Casemiro", "Marquinhos"]', 0, 'medium', 'players'),
('Que jugador tiene el record de mas Balones de Oro?', '["Ronaldo", "Messi", "Cruyff", "Platini"]', 1, 'easy', 'players'),
('En que club juega Jude Bellingham?', '["Manchester City", "Real Madrid", "Bayern Munich", "Barcelona"]', 1, 'easy', 'players'),
('De que pais es Lamine Yamal?', '["Francia", "Marruecos", "Espana", "Portugal"]', 2, 'easy', 'players'),
('Que posicion juega Manuel Neuer?', '["Defensa", "Mediocampista", "Delantero", "Portero"]', 3, 'easy', 'players'),
('Quien es el maximo goleador historico de la Premier League?', '["Rooney", "Shearer", "Henry", "Lampard"]', 1, 'medium', 'players'),
('De que pais es Vinicius Junior?', '["Argentina", "Portugal", "Brasil", "Colombia"]', 2, 'easy', 'players'),
('Que jugador es conocido como CR7?', '["Cristiano Ronaldo", "Carlos Riquelme", "Claudio Reyna", "Cesc Rodriguez"]', 0, 'easy', 'players'),
('En que club juega Pedri (2026)?', '["Real Madrid", "Barcelona", "Atletico Madrid", "Manchester City"]', 1, 'easy', 'players'),
('Que posicion juega Kevin De Bruyne?', '["Defensa", "Mediocampista", "Delantero", "Portero"]', 1, 'easy', 'players'),
('De que pais es Mohamed Salah?', '["Marruecos", "Tunisia", "Egipto", "Algeria"]', 2, 'easy', 'players'),
('Quien gano el Balon de Oro en 2023?', '["Haaland", "Mbappe", "Messi", "Bellingham"]', 2, 'medium', 'players'),
('Que jugador colombiano juega en el Liverpool?', '["James Rodriguez", "Luis Diaz", "Juan Cuadrado", "Falcao"]', 1, 'easy', 'players'),
('De que pais es Son Heung-min?', '["Japon", "China", "Corea del Sur", "Tailandia"]', 2, 'easy', 'players'),
('Que numero usa Neymar en la seleccion de Brasil?', '["7", "9", "10", "11"]', 2, 'easy', 'players'),

-- GENERAL (120 preguntas)
('Cuantos jugadores hay en un equipo de futbol sala?', '["5", "7", "9", "11"]', 0, 'easy', 'general'),
('Que trofeo se entrega al ganador del Mundial?', '["Copa Jules Rimet", "Copa FIFA", "Copa de Oro", "Copa del Mundo FIFA"]', 3, 'easy', 'general'),
('De que material esta hecho el trofeo del Mundial actual?', '["Plata", "Oro de 18 quilates", "Bronce", "Platino"]', 1, 'medium', 'general'),
('Cuanto pesa el trofeo del Mundial?', '["3.8 kg", "6.175 kg", "8 kg", "4.5 kg"]', 1, 'hard', 'general'),
('Que organizacion organiza el Mundial de futbol?', '["UEFA", "CONMEBOL", "FIFA", "IOC"]', 2, 'easy', 'general'),
('Cada cuantos anos se juega el Mundial?', '["2", "3", "4", "5"]', 2, 'easy', 'general'),
('Que significa FIFA?', '["Federation Int. Football Assoc.", "Federacion Int. de Futbol Asociado", "Federation Internationale de Football Association", "Federacion Internacional de Futbol Amateur"]', 2, 'medium', 'general'),
('Que balon se usa en el Mundial 2026?', '["Telstar", "Brazuca", "Al Rihla", "Aun no se anuncia"]', 3, 'medium', 'general'),
('Cuantas confederaciones de futbol existen?', '["4", "5", "6", "7"]', 2, 'medium', 'general'),
('Que confederacion agrupa a los paises sudamericanos?', '["UEFA", "CONCACAF", "CONMEBOL", "AFC"]', 2, 'easy', 'general'),
('Que confederacion agrupa a los paises europeos?', '["FIFA", "UEFA", "CONMEBOL", "AFC"]', 1, 'easy', 'general'),
('Cual es el estadio mas grande del mundo?', '["Camp Nou", "Wembley", "Rungrado (Corea del Norte)", "Maracana"]', 2, 'hard', 'general'),
('Que color es la tarjeta que introduce el VAR en caso de revision?', '["Azul", "Verde", "No hay tarjeta especial", "Blanca"]', 2, 'medium', 'general'),
('Cuantos arbitros asistentes hay en un partido?', '["1", "2", "3", "4"]', 1, 'easy', 'general'),
('Que es un hat-trick?', '["3 goles de un jugador", "3 tarjetas amarillas", "3 corners seguidos", "3 faltas"]', 0, 'easy', 'general'),
('Cuanto mide una cancha de futbol profesional de largo?', '["90-120 metros", "80-100 metros", "100-110 metros", "105 metros exacto"]', 0, 'medium', 'general'),
('Que es la Champions League?', '["Torneo de selecciones", "Torneo de clubes europeos", "Liga americana", "Copa del mundo de clubes"]', 1, 'easy', 'general'),
('Que equipo ha ganado mas Champions League?', '["Barcelona", "AC Milan", "Real Madrid", "Bayern Munich"]', 2, 'easy', 'general'),
('Que es un derbi?', '["Partido entre equipos de la misma ciudad o region", "Partido amistoso", "Partido de eliminatoria", "Partido de entrenamiento"]', 0, 'easy', 'general'),
('Que pais invento el futbol moderno?', '["Brasil", "Italia", "Inglaterra", "Espana"]', 2, 'easy', 'general'),
('En que ano se fundo la FIFA?', '["1900", "1904", "1910", "1920"]', 1, 'medium', 'general'),
('Que es el Fair Play?', '["Juego limpio y deportividad", "Tipo de falta", "Regla del offside", "Sistema de puntos"]', 0, 'easy', 'general'),
('Que posicion es el numero 9 tradicionalmente?', '["Portero", "Defensa", "Mediocampista", "Delantero centro"]', 3, 'easy', 'general'),
('Que es un penalti?', '["Tiro desde 11 metros por falta en el area", "Tiro libre", "Corner", "Saque de banda"]', 0, 'easy', 'general'),
('Cuantos continentes han organizado un Mundial?', '["3", "4", "5", "6"]', 2, 'medium', 'general'),
('Que es la Ligue 1?', '["Liga de Espana", "Liga de Francia", "Liga de Italia", "Liga de Alemania"]', 1, 'easy', 'general'),
('Que es la Bundesliga?', '["Liga de Espana", "Liga de Francia", "Liga de Italia", "Liga de Alemania"]', 3, 'easy', 'general'),
('Que es La Liga?', '["Liga de Espana", "Liga de Francia", "Liga de Italia", "Liga de Alemania"]', 0, 'easy', 'general'),
('Que es la Serie A?', '["Liga de Espana", "Liga de Francia", "Liga de Italia", "Liga de Alemania"]', 2, 'easy', 'general'),
('Cuantos segundos tiene un arquero para sacar el balon despues de atraparlo?', '["4", "6", "8", "10"]', 1, 'medium', 'general');
