-- =====================================================================
-- Trivia extra v1 — +350 preguntas para llegar a ~500 total
-- =====================================================================
--
-- Distribución:
--   easy:   ~120 (mix balanceado entre 6 categorías)
--   medium: ~140
--   hard:   ~90
--
-- Categorías:
--   general:        cultura general fútbol
--   history:        Mundiales 1930-2022, hitos historicos
--   players:        Pele, Maradona, Messi, CR7, Mbappe, Haaland, etc.
--   rules:          reglamento, VAR, offside, tarjetas
--   stats:          records, numeros, estadisticas
--   world_cup_2026: Canada/USA/Mexico, sedes, novedades
--
-- options = jsonb array de 4 strings
-- correct_option = index 0-3 de la opcion correcta
-- =====================================================================

BEGIN;

INSERT INTO trivia_questions (question, options, correct_option, difficulty, category) VALUES

-- ───────────────────────────────────────────────
-- HISTORIA (60 preguntas)
-- ───────────────────────────────────────────────
('En que ano se jugo el primer Mundial?', '["1928", "1930", "1932", "1934"]'::jsonb, 1, 'easy', 'history'),
('Que pais organizo el primer Mundial?', '["Brasil", "Italia", "Uruguay", "Argentina"]'::jsonb, 2, 'easy', 'history'),
('Quien gano el primer Mundial?', '["Argentina", "Uruguay", "Italia", "Brasil"]'::jsonb, 1, 'easy', 'history'),
('Cuantos Mundiales gano Brasil hasta 2022?', '["3", "4", "5", "6"]'::jsonb, 2, 'easy', 'history'),
('En que ano gano Argentina su primer Mundial?', '["1974", "1978", "1982", "1986"]'::jsonb, 1, 'easy', 'history'),
('Quien gano el Mundial 1986?', '["Argentina", "Alemania", "Brasil", "Italia"]'::jsonb, 0, 'easy', 'history'),
('Quien gano el Mundial 2014?', '["Argentina", "Brasil", "Alemania", "Espana"]'::jsonb, 2, 'easy', 'history'),
('Quien gano el Mundial 2018?', '["Croacia", "Francia", "Belgica", "Inglaterra"]'::jsonb, 1, 'easy', 'history'),
('Quien gano el Mundial 2022?', '["Francia", "Argentina", "Marruecos", "Croacia"]'::jsonb, 1, 'easy', 'history'),
('Donde se jugo el Mundial 2022?', '["Emiratos", "Qatar", "Arabia Saudita", "Kuwait"]'::jsonb, 1, 'easy', 'history'),
('Donde se jugo el Mundial 2018?', '["Rusia", "Polonia", "Ucrania", "Alemania"]'::jsonb, 0, 'easy', 'history'),
('Donde se jugo el Mundial 2014?', '["Argentina", "Brasil", "Chile", "Uruguay"]'::jsonb, 1, 'easy', 'history'),
('Donde se jugo el Mundial 2010?', '["Nigeria", "Egipto", "Sudafrica", "Camerun"]'::jsonb, 2, 'easy', 'history'),
('Quien gano el Mundial 2010?', '["Holanda", "Espana", "Alemania", "Brasil"]'::jsonb, 1, 'easy', 'history'),
('Cuantos Mundiales gano Alemania en total?', '["2", "3", "4", "5"]'::jsonb, 2, 'medium', 'history'),
('Cuantos Mundiales gano Italia en total?', '["2", "3", "4", "5"]'::jsonb, 2, 'medium', 'history'),
('Cuantos Mundiales gano Argentina hasta 2022?', '["1", "2", "3", "4"]'::jsonb, 2, 'easy', 'history'),
('Que pais perdio 3 finales seguidas de Mundial?', '["Argentina", "Holanda", "Brasil", "Alemania"]'::jsonb, 1, 'medium', 'history'),
('En que Mundial debuto el VAR?', '["2014", "2018", "2022", "Sub-20"]'::jsonb, 1, 'medium', 'history'),
('Que pais gano el Mundial 2002?', '["Brasil", "Alemania", "Italia", "Argentina"]'::jsonb, 0, 'easy', 'history'),
('Donde se jugo el Mundial 2002?', '["China", "Corea/Japon", "Japon", "Tailandia"]'::jsonb, 1, 'medium', 'history'),
('Quien gano el Mundial 1998?', '["Brasil", "Francia", "Italia", "Croacia"]'::jsonb, 1, 'easy', 'history'),
('Donde se jugo el Mundial 1994?', '["Mexico", "USA", "Canada", "Brasil"]'::jsonb, 1, 'medium', 'history'),
('Quien gano el Mundial 1994?', '["Brasil", "Italia", "Suecia", "Argentina"]'::jsonb, 0, 'medium', 'history'),
('Donde se jugo el Mundial 1990?', '["Espana", "Italia", "Mexico", "Alemania"]'::jsonb, 1, 'medium', 'history'),
('Quien gano el Mundial 1990?', '["Alemania", "Argentina", "Italia", "Inglaterra"]'::jsonb, 0, 'medium', 'history'),
('Quien gano el Mundial 1982?', '["Brasil", "Italia", "Alemania", "Polonia"]'::jsonb, 1, 'medium', 'history'),
('Quien gano el Mundial 1974?', '["Holanda", "Alemania", "Polonia", "Brasil"]'::jsonb, 1, 'medium', 'history'),
('Quien gano el Mundial 1970?', '["Italia", "Brasil", "Alemania", "Uruguay"]'::jsonb, 1, 'medium', 'history'),
('Quien gano el Mundial 1966?', '["Inglaterra", "Alemania", "Portugal", "Brasil"]'::jsonb, 0, 'medium', 'history'),
('Cuantos Mundiales gano Uruguay?', '["1", "2", "3", "4"]'::jsonb, 1, 'medium', 'history'),
('Cuantos Mundiales gano Francia?', '["1", "2", "3", "4"]'::jsonb, 1, 'medium', 'history'),
('Cuantos Mundiales gano Espana?', '["0", "1", "2", "3"]'::jsonb, 1, 'medium', 'history'),
('Cuantos Mundiales gano Inglaterra?', '["0", "1", "2", "3"]'::jsonb, 1, 'medium', 'history'),
('En que Mundial Argentina perdio la final 1-0 con Alemania?', '["1986", "1990", "2014", "2018"]'::jsonb, 1, 'hard', 'history'),
('Quien marco el gol "Mano de Dios"?', '["Pele", "Maradona", "Messi", "Romario"]'::jsonb, 1, 'easy', 'history'),
('En que partido fue la "Mano de Dios"?', '["Argentina-Inglaterra 1986", "Argentina-Belgica 1986", "Argentina-Alemania 1986", "Argentina-Brasil 1990"]'::jsonb, 0, 'medium', 'history'),
('Cual fue la primera seleccion africana en llegar a cuartos de Mundial?', '["Nigeria", "Senegal", "Camerun", "Marruecos"]'::jsonb, 2, 'hard', 'history'),
('En que Mundial Camerun llego a cuartos por primera vez?', '["1986", "1990", "1994", "1998"]'::jsonb, 1, 'hard', 'history'),
('Cual fue la primera seleccion africana en llegar a semis de Mundial?', '["Senegal", "Ghana", "Marruecos", "Sudafrica"]'::jsonb, 2, 'medium', 'history'),
('En que Mundial Marruecos llego a semifinales?', '["2018", "2022", "1986", "2026"]'::jsonb, 1, 'easy', 'history'),
('Donde se jugo el Mundial 1962?', '["Brasil", "Mexico", "Chile", "Argentina"]'::jsonb, 2, 'hard', 'history'),
('Quien gano el Mundial 1962?', '["Brasil", "Uruguay", "Argentina", "Hungria"]'::jsonb, 0, 'hard', 'history'),
('Donde se jugo el Mundial 1954?', '["Suecia", "Brasil", "Suiza", "Alemania"]'::jsonb, 2, 'hard', 'history'),
('Quien gano el Mundial 1954?', '["Hungria", "Alemania", "Italia", "Uruguay"]'::jsonb, 1, 'hard', 'history'),
('Que ano fue el "Maracanazo"?', '["1948", "1950", "1954", "1958"]'::jsonb, 1, 'medium', 'history'),
('Quien gano contra Brasil en el Maracanazo?', '["Argentina", "Uruguay", "Italia", "Suecia"]'::jsonb, 1, 'medium', 'history'),
('Cuantos Mundiales se jugaron en Mexico hasta 2022?', '["1", "2", "3", "4"]'::jsonb, 1, 'medium', 'history'),
('En que ano Mexico organizo su primer Mundial?', '["1966", "1970", "1974", "1978"]'::jsonb, 1, 'medium', 'history'),
('Por que se canceló el Mundial 1942?', '["Guerra Mundial", "Crisis economica", "Pandemia", "Disputa FIFA"]'::jsonb, 0, 'medium', 'history'),
('Cuantos paises participaron del primer Mundial?', '["8", "10", "13", "16"]'::jsonb, 2, 'hard', 'history'),
('Que seleccion fue la "Naranja Mecanica"?', '["Brasil", "Holanda", "Alemania", "Hungria"]'::jsonb, 1, 'medium', 'history'),
('Quien era el DT de la Naranja Mecanica?', '["Cruyff", "Michels", "Rinus Michels", "Van Gaal"]'::jsonb, 1, 'hard', 'history'),
('En que Mundial Italia gano por penales contra Francia?', '["1998", "2002", "2006", "2010"]'::jsonb, 2, 'medium', 'history'),
('En que Mundial Zidane fue expulsado en la final por el cabezazo a Materazzi?', '["1998", "2002", "2006", "2010"]'::jsonb, 2, 'medium', 'history'),
('Cuantos goles hizo Argentina en la final 1986 contra Alemania?', '["2", "3", "4", "5"]'::jsonb, 1, 'hard', 'history'),
('Donde fue la final del Mundial 1978?', '["Buenos Aires", "Cordoba", "Rosario", "Mar del Plata"]'::jsonb, 0, 'medium', 'history'),
('Cual fue el primer Mundial transmitido por TV?', '["1934", "1954", "1958", "1962"]'::jsonb, 1, 'hard', 'history'),
('En que ano se introdujo el formato actual de 32 equipos?', '["1990", "1994", "1998", "2002"]'::jsonb, 2, 'hard', 'history'),

-- ───────────────────────────────────────────────
-- JUGADORES (70 preguntas)
-- ───────────────────────────────────────────────
('Quien gano 8 Balones de Oro?', '["Cristiano", "Messi", "Pele", "Maradona"]'::jsonb, 1, 'easy', 'players'),
('Cuantos Balones de Oro ganó Cristiano Ronaldo?', '["3", "4", "5", "6"]'::jsonb, 2, 'easy', 'players'),
('Quien hizo "La Mano de Dios"?', '["Pele", "Maradona", "Romario", "Zico"]'::jsonb, 1, 'easy', 'players'),
('Quien es el maximo goleador historico del Real Madrid?', '["Raul", "Cristiano", "Hierro", "Di Stefano"]'::jsonb, 1, 'easy', 'players'),
('Quien es el maximo goleador historico del Barcelona?', '["Cruyff", "Messi", "Suarez", "Romario"]'::jsonb, 1, 'easy', 'players'),
('Cuantos Mundiales gano Pele?', '["1", "2", "3", "4"]'::jsonb, 2, 'easy', 'players'),
('Pele era de que pais?', '["Argentina", "Brasil", "Portugal", "Uruguay"]'::jsonb, 1, 'easy', 'players'),
('Maradona era de que pais?', '["Argentina", "Brasil", "Uruguay", "Chile"]'::jsonb, 0, 'easy', 'players'),
('Messi es de que ciudad?', '["Buenos Aires", "Rosario", "Cordoba", "Mendoza"]'::jsonb, 1, 'easy', 'players'),
('Mbappe es de que pais?', '["Camerun", "Argelia", "Francia", "Senegal"]'::jsonb, 2, 'easy', 'players'),
('Haaland es de que pais?', '["Suecia", "Dinamarca", "Noruega", "Islandia"]'::jsonb, 2, 'easy', 'players'),
('Cristiano Ronaldo es de que pais?', '["Brasil", "Espana", "Portugal", "Italia"]'::jsonb, 2, 'easy', 'players'),
('Neymar es de que pais?', '["Brasil", "Portugal", "Argentina", "Uruguay"]'::jsonb, 0, 'easy', 'players'),
('Lewandowski es de que pais?', '["Republica Checa", "Polonia", "Eslovaquia", "Ucrania"]'::jsonb, 1, 'easy', 'players'),
('Modric es de que pais?', '["Serbia", "Bosnia", "Croacia", "Eslovenia"]'::jsonb, 2, 'easy', 'players'),
('Quien gano el Balon de Oro 2023?', '["Mbappe", "Haaland", "Messi", "Bellingham"]'::jsonb, 2, 'medium', 'players'),
('Quien gano el Balon de Oro 2022?', '["Benzema", "Messi", "Mbappe", "Haaland"]'::jsonb, 0, 'medium', 'players'),
('Quien gano el Balon de Oro 2021?', '["Lewandowski", "Messi", "Jorginho", "Benzema"]'::jsonb, 1, 'medium', 'players'),
('Cuantos goles hizo Messi en Mundiales (hasta 2022)?', '["10", "11", "13", "15"]'::jsonb, 2, 'medium', 'players'),
('Cuantos goles hizo Cristiano en Mundiales (hasta 2022)?', '["6", "7", "8", "10"]'::jsonb, 2, 'medium', 'players'),
('Maximo goleador de un Mundial fue Just Fontaine. Cuantos goles?', '["10", "11", "13", "15"]'::jsonb, 2, 'hard', 'players'),
('Just Fontaine era de que pais?', '["Francia", "Belgica", "Suiza", "Marruecos"]'::jsonb, 0, 'hard', 'players'),
('Quien hizo mas hat-tricks en Mundiales?', '["Pele", "Klose", "Just Fontaine", "Sandor Kocsis"]'::jsonb, 3, 'hard', 'players'),
('Klose es de que pais?', '["Alemania", "Polonia", "Republica Checa", "Austria"]'::jsonb, 0, 'easy', 'players'),
('Quien fue MVP del Mundial 2022?', '["Mbappe", "Messi", "Di Maria", "Modric"]'::jsonb, 1, 'easy', 'players'),
('Quien gano la Bota de Oro del Mundial 2022?', '["Messi", "Mbappe", "Giroud", "Alvarez"]'::jsonb, 1, 'medium', 'players'),
('Cuantos goles hizo Mbappe en la final 2022?', '["1", "2", "3", "4"]'::jsonb, 2, 'medium', 'players'),
('Quien era el arquero de Argentina en el Mundial 2022?', '["Romero", "Andrada", "Dibu Martinez", "Armani"]'::jsonb, 2, 'easy', 'players'),
('Quien era el arquero de Francia en el Mundial 2022?', '["Lloris", "Maignan", "Areola", "Mandanda"]'::jsonb, 0, 'medium', 'players'),
('Quien hizo el gol del 4-2 final de Argentina 2022 contra Francia?', '["Messi", "Mbappe", "Montiel", "Di Maria"]'::jsonb, 0, 'medium', 'players'),
('Quien fallo el penal para Francia en la final 2022?', '["Mbappe", "Coman/Tchouameni", "Giroud", "Griezmann"]'::jsonb, 1, 'medium', 'players'),
('Quien hizo el gol mas rapido de Mundial?', '["Hakan Sukur", "Klose", "Maradona", "Pele"]'::jsonb, 0, 'hard', 'players'),
('Hakan Sukur lo hizo en cuantos segundos?', '["8", "10", "11", "13"]'::jsonb, 2, 'hard', 'players'),
('Quien es el arquero con mas Mundiales jugados?', '["Buffon", "Casillas", "Higuita", "Carbajal"]'::jsonb, 3, 'hard', 'players'),
('Cuantos Mundiales jugo Antonio Carbajal?', '["3", "4", "5", "6"]'::jsonb, 2, 'hard', 'players'),
('De que pais era Carbajal?', '["Argentina", "Mexico", "Brasil", "Espana"]'::jsonb, 1, 'medium', 'players'),
('Quien hizo el primer gol con VAR en un Mundial?', '["Griezmann", "Mbappe", "Cristiano", "Modric"]'::jsonb, 0, 'hard', 'players'),
('Quien era el capitan de Espana cuando ganaron el Mundial 2010?', '["Iniesta", "Xavi", "Casillas", "Puyol"]'::jsonb, 2, 'medium', 'players'),
('Quien hizo el gol de la final Espana 2010?', '["Villa", "Iniesta", "Xavi", "Torres"]'::jsonb, 1, 'medium', 'players'),
('Cuantos goles hizo Italia en la final 2006?', '["1", "2", "3", "4"]'::jsonb, 0, 'hard', 'players'),
('Quien convirtio el penal decisivo en la final 2006?', '["Trezeguet", "Materazzi", "Grosso", "Pirlo"]'::jsonb, 2, 'hard', 'players'),
('Diego Maradona jugo en cuantos Mundiales?', '["3", "4", "5", "6"]'::jsonb, 1, 'medium', 'players'),
('En que Mundial Maradona fue capitan de Argentina campeona?', '["1978", "1982", "1986", "1990"]'::jsonb, 2, 'easy', 'players'),
('Quien marco el "Gol del Siglo" de Maradona?', '["Maradona", "Burruchaga", "Valdano", "Caniggia"]'::jsonb, 0, 'easy', 'players'),
('Cuantos rivales esquivo Maradona en el "Gol del Siglo"?', '["3", "4", "5", "6"]'::jsonb, 2, 'medium', 'players'),
('Quien era el DT de Argentina cuando ganaron Mexico 86?', '["Menotti", "Bilardo", "Sabella", "Scaloni"]'::jsonb, 1, 'medium', 'players'),
('Quien era el DT de Argentina cuando ganaron Qatar 2022?', '["Bilardo", "Sabella", "Scaloni", "Pekerman"]'::jsonb, 2, 'easy', 'players'),
('Quien era el DT de Espana 2010?', '["Aragones", "Del Bosque", "Casillas", "Hierro"]'::jsonb, 1, 'medium', 'players'),
('Quien era el DT de Francia 2018 y 2022?', '["Domenech", "Deschamps", "Henry", "Zidane"]'::jsonb, 1, 'easy', 'players'),
('Deschamps gano la Copa del Mundo como jugador en?', '["1990", "1994", "1998", "2002"]'::jsonb, 2, 'medium', 'players'),
('Quien era el DT de Brasil 2002?', '["Felipao", "Parreira", "Dunga", "Tite"]'::jsonb, 0, 'medium', 'players'),
('En el Mundial 2002 cuantos goles hizo Ronaldo Nazario?', '["6", "8", "10", "12"]'::jsonb, 1, 'medium', 'players'),
('Cuantos goles hizo Ronaldo Nazario en TODOS los Mundiales?', '["12", "13", "15", "17"]'::jsonb, 2, 'hard', 'players'),
('Quien gano la Bota de Oro Mundial 2014?', '["Messi", "James Rodriguez", "Muller", "Neymar"]'::jsonb, 1, 'hard', 'players'),
('Quien gano la Bota de Oro Mundial 2018?', '["Cavani", "Kane", "Lukaku", "Griezmann"]'::jsonb, 1, 'medium', 'players'),
('Quien gano el premio Yashin (mejor arquero) Mundial 2022?', '["Lloris", "Dibu Martinez", "Onana", "Bono"]'::jsonb, 1, 'medium', 'players'),
('Cuantos jugadores tiene un equipo titular en futbol?', '["10", "11", "12", "13"]'::jsonb, 1, 'easy', 'players'),
('Quien fue el arquero brasileno que el "Maracanazo" lo marco?', '["Gilmar", "Barbosa", "Garrincha", "Castilho"]'::jsonb, 1, 'hard', 'players'),
('De que pais es Vinicius Jr?', '["Argentina", "Portugal", "Brasil", "Espana"]'::jsonb, 2, 'easy', 'players'),
('De que pais es Bellingham?', '["Inglaterra", "Belgica", "Holanda", "Alemania"]'::jsonb, 0, 'easy', 'players'),
('De que pais es Pedri?', '["Espana", "Portugal", "Italia", "Francia"]'::jsonb, 0, 'medium', 'players'),
('De que pais es Erling Haaland?', '["Suecia", "Noruega", "Dinamarca", "Islandia"]'::jsonb, 1, 'easy', 'players'),
('Quien gano el Balon de Oro 2024?', '["Vinicius", "Rodri", "Bellingham", "Yamal"]'::jsonb, 1, 'medium', 'players'),
('Cuanto saco Messi de capitan de Argentina, en cantidad de partidos?', '["+100", "+150", "+170", "+200"]'::jsonb, 2, 'hard', 'players'),
('Quien era capitan de Brasil en 2022?', '["Neymar", "Casemiro", "Thiago Silva", "Marquinhos"]'::jsonb, 2, 'medium', 'players'),
('Quien fue Bota de Oro Mundial 2010?', '["Villa", "Forlan", "Schweinsteiger", "Muller"]'::jsonb, 3, 'hard', 'players'),
('Quien fue MVP del Mundial 2010?', '["Villa", "Forlan", "Iniesta", "Casillas"]'::jsonb, 1, 'hard', 'players'),
('De que pais es Diego Forlan?', '["Argentina", "Chile", "Uruguay", "Peru"]'::jsonb, 2, 'medium', 'players'),
('Cuantas Champions League gano Cristiano Ronaldo?', '["3", "4", "5", "6"]'::jsonb, 2, 'medium', 'players'),
('Cuantas Champions League gano Messi?', '["3", "4", "5", "6"]'::jsonb, 1, 'medium', 'players'),

-- ───────────────────────────────────────────────
-- REGLAS (50 preguntas)
-- ───────────────────────────────────────────────
('Cuantos minutos dura un partido reglamentario?', '["80", "90", "100", "120"]'::jsonb, 1, 'easy', 'rules'),
('Cuantos jugadores son por equipo en la cancha?', '["10", "11", "12", "13"]'::jsonb, 1, 'easy', 'rules'),
('Cuantos suplentes puede cambiar un equipo en un partido oficial actual?', '["3", "5", "6", "7"]'::jsonb, 1, 'medium', 'rules'),
('Que tarjeta significa expulsion?', '["Amarilla", "Roja", "Azul", "Verde"]'::jsonb, 1, 'easy', 'rules'),
('Cuantas tarjetas amarillas suman roja?', '["2", "3", "4", "5"]'::jsonb, 0, 'easy', 'rules'),
('Que es un tiro penal?', '["Tiro libre directo", "Tiro desde el punto a 11m del arco", "Saque de banda", "Saque de esquina"]'::jsonb, 1, 'easy', 'rules'),
('A cuantos metros se tira un penal?', '["9", "11", "12", "15"]'::jsonb, 1, 'easy', 'rules'),
('Cuantos minutos dura cada tiempo extra (alargue)?', '["10", "15", "20", "30"]'::jsonb, 1, 'easy', 'rules'),
('Cuanto dura el descanso entre tiempos?', '["10 min", "15 min", "20 min", "30 min"]'::jsonb, 1, 'easy', 'rules'),
('Que es el offside?', '["Estar adelante del defensor cuando le pasan la pelota", "Tirar fuera de la cancha", "Pisar la pelota", "Cabecear sin pelota"]'::jsonb, 0, 'easy', 'rules'),
('Como se llama el reinicio cuando la pelota sale por la linea de fondo y la toco un defensor?', '["Saque de banda", "Tiro de esquina", "Tiro libre", "Saque de arco"]'::jsonb, 1, 'easy', 'rules'),
('Como se llama el reinicio cuando la pelota sale por la linea de fondo y la toco un atacante?', '["Saque de banda", "Tiro de esquina", "Saque de arco", "Tiro libre"]'::jsonb, 2, 'medium', 'rules'),
('Cuantos arqueros puede tener un equipo en la cancha?', '["1", "2", "3", "4"]'::jsonb, 0, 'easy', 'rules'),
('VAR significa?', '["Video Assistant Referee", "Visual Active Referee", "Verified Action Replay", "Video Action Review"]'::jsonb, 0, 'medium', 'rules'),
('Donde esta el VAR durante un partido?', '["Junto al banco", "En cabina aparte", "En el centro del campo", "En vestuarios"]'::jsonb, 1, 'medium', 'rules'),
('Cuantos arbitros hay en la cancha (sin contar VAR)?', '["1", "2", "3", "4"]'::jsonb, 2, 'medium', 'rules'),
('Como se llaman los 2 arbitros asistentes en las bandas?', '["Asistentes / Lineman", "Sub-arbitros", "Veedores", "Jueces"]'::jsonb, 0, 'medium', 'rules'),
('En un Mundial, cuantos puntos vale ganar en fase de grupos?', '["1", "2", "3", "4"]'::jsonb, 2, 'easy', 'rules'),
('Cuantos puntos vale empatar?', '["0", "1", "2", "3"]'::jsonb, 1, 'easy', 'rules'),
('Si un equipo es local cuando es la segunda mitad de un alargue?', '["El que sorteo", "El que gano la moneda", "El que define la pelota", "No hay local en alargue"]'::jsonb, 3, 'hard', 'rules'),
('Si dos equipos terminan con mismos puntos en grupos, que criterio sigue primero?', '["Goles a favor", "Diferencia de goles", "Resultado entre ambos", "Tarjetas"]'::jsonb, 1, 'medium', 'rules'),
('Cual es el pinguino del medio del arco?', '["Linea de cal", "Linea de gol", "Linea de penal", "Linea de meta"]'::jsonb, 1, 'medium', 'rules'),
('Cuantos jugadores se necesitan minimo para que un partido continue?', '["6", "7", "8", "9"]'::jsonb, 1, 'medium', 'rules'),
('Que pasa si un equipo queda con menos de 7 por expulsiones?', '["Continua", "Se suspende", "Pierde 3-0", "Se decide en penales"]'::jsonb, 1, 'medium', 'rules'),
('Cuantos minutos despues del inicio se puede pedir cambio?', '["No hay limite", "Solo en descanso", "Despues de 15 min", "Antes del minuto 80"]'::jsonb, 0, 'medium', 'rules'),
('Cuando se introdujo la "ventana" obligatoria de cambio (3 ventanas)?', '["1998", "2008", "2014", "2020"]'::jsonb, 3, 'hard', 'rules'),
('En el Mundial 2022 cuantos cambios podia hacer un equipo?', '["3", "5", "6", "7"]'::jsonb, 1, 'medium', 'rules'),
('Cuantos puede hacer un equipo en tiempo extra (adicional a los del partido)?', '["1", "2", "3", "5"]'::jsonb, 0, 'hard', 'rules'),
('Si un jugador toca pelota con el brazo accidentalmente en el area, es penal?', '["Siempre", "Nunca", "Depende: si hay intencion o ventaja", "Solo si toca la mano"]'::jsonb, 2, 'medium', 'rules'),
('Que es un fuera de juego pasivo?', '["Sin tocar la pelota ni interferir", "Tocar la pelota con la mano", "Estar mal posicionado", "Ofender al arbitro"]'::jsonb, 0, 'medium', 'rules'),
('Quien creo el reglamento moderno del futbol?', '["FIFA", "Premier League", "FA inglesa", "UEFA"]'::jsonb, 2, 'hard', 'rules'),
('En que ano se fundo la FA?', '["1863", "1888", "1900", "1920"]'::jsonb, 0, 'hard', 'rules'),
('Cuantos arbitros adicionales tiene un partido importante (incluyendo 4to y VAR)?', '["3", "4", "5", "6"]'::jsonb, 1, 'hard', 'rules'),
('Cual es la duracion oficial del "tiempo adicional" por lesiones, en promedio?', '["1-3 min", "3-7 min", "5-10 min", "Sin tope"]'::jsonb, 3, 'medium', 'rules'),
('Si el partido termina empatado en eliminatorias de Mundial, que sigue?', '["Empate", "Penales", "Tiempo suplementario", "Sorteo"]'::jsonb, 2, 'easy', 'rules'),
('Si el alargue termina empatado, que sigue?', '["Sorteo", "Penales", "Otro alargue", "Se repite el partido"]'::jsonb, 1, 'easy', 'rules'),
('Cuantos penales se tiran inicialmente en una definicion?', '["3", "5", "7", "10"]'::jsonb, 1, 'medium', 'rules'),
('Si despues de 5 penales sigue empate, que pasa?', '["Sorteo", "Muerte subita", "Se repite", "Goles fuera"]'::jsonb, 1, 'medium', 'rules'),
('Un autogol cuenta como del jugador o del equipo rival?', '["Del jugador", "Del equipo rival", "Se anula", "Se reparte"]'::jsonb, 1, 'medium', 'rules'),
('Si el balon toca el arbitro y entra al arco, es gol?', '["Si", "No", "Depende de si fue intencional", "Se repite la jugada"]'::jsonb, 1, 'hard', 'rules'),
('Cuanto pesa una pelota oficial FIFA?', '["350-400g", "410-450g", "460-500g", "510-550g"]'::jsonb, 1, 'hard', 'rules'),
('Que circunferencia debe tener una pelota oficial FIFA?', '["60-65 cm", "68-70 cm", "72-75 cm", "78-80 cm"]'::jsonb, 1, 'hard', 'rules'),
('Cuanto mide el arco de futbol?', '["7.32m x 2.44m", "8m x 2.5m", "7m x 2m", "6.5m x 2.2m"]'::jsonb, 0, 'hard', 'rules'),
('Cuanto mide una cancha oficial FIFA (largo)?', '["90-100m", "100-110m", "100-130m", "110-140m"]'::jsonb, 2, 'hard', 'rules'),
('Cuanto mide una cancha oficial FIFA (ancho)?', '["50-60m", "64-75m", "70-80m", "80-90m"]'::jsonb, 1, 'hard', 'rules'),
('Que es la regla de "back-pass" al arquero?', '["Pase con cabeza al arquero", "Pase con pie al arquero, no puede agarrar la pelota", "Pase de saque, no puede agarrar", "Cualquier pase, no puede agarrar"]'::jsonb, 1, 'medium', 'rules'),
('En que ano se introdujo la regla del "back-pass"?', '["1990", "1992", "1995", "1998"]'::jsonb, 1, 'hard', 'rules'),
('Si el arquero levanta un back-pass con las manos, que es?', '["Tiro libre indirecto", "Tiro libre directo", "Penal", "Amarilla"]'::jsonb, 0, 'hard', 'rules'),
('Cuanto vale el primer Mundial femenino?', '["1991", "1995", "1999", "2003"]'::jsonb, 0, 'hard', 'rules'),
('Cuantos equipos juegan el Mundial femenino actual?', '["16", "24", "32", "48"]'::jsonb, 2, 'hard', 'rules'),

-- ───────────────────────────────────────────────
-- ESTADISTICAS (50 preguntas)
-- ───────────────────────────────────────────────
('Cuantos goles totales tuvo el Mundial 2022?', '["150", "172", "190", "215"]'::jsonb, 1, 'medium', 'stats'),
('Cuantos partidos se juegan en un Mundial de 32 equipos (sin sumar repechaje)?', '["48", "56", "64", "72"]'::jsonb, 2, 'medium', 'stats'),
('Cual es el mayor gol-promedio por partido en un Mundial?', '["3.0", "4.0", "5.4", "6.1"]'::jsonb, 2, 'hard', 'stats'),
('En que Mundial fue el mayor gol-promedio (5.38)?', '["1930", "1938", "1954", "1962"]'::jsonb, 2, 'hard', 'stats'),
('Cual ha sido el partido con mas goles en un Mundial?', '["Brasil 7 - Suecia 1", "Hungria 10 - El Salvador 1", "Austria 7 - Suiza 5", "Brasil 7 - Alemania 1"]'::jsonb, 1, 'hard', 'stats'),
('Quien tiene el record de Mundiales jugados como jugador?', '["Maldini", "Buffon", "Carbajal", "Matthaus"]'::jsonb, 3, 'hard', 'stats'),
('Cuantos Mundiales jugo Lothar Matthaus?', '["3", "4", "5", "6"]'::jsonb, 2, 'hard', 'stats'),
('Cual fue la asistencia mas alta a un partido de Mundial?', '["120k", "150k", "170k", "200k"]'::jsonb, 3, 'hard', 'stats'),
('Donde fue el partido de 200k asistentes (Maracana 1950)?', '["Sao Paulo", "Rio de Janeiro", "Brasilia", "Belo Horizonte"]'::jsonb, 1, 'medium', 'stats'),
('Cuantos paises participaron en eliminatorias del Mundial 2022?', '["180+", "200+", "210+", "220+"]'::jsonb, 2, 'hard', 'stats'),
('Cuantos goles hizo Brasil en TODA su historia de Mundiales?', '["220+", "230+", "240+", "250+"]'::jsonb, 2, 'hard', 'stats'),
('Cuantos Mundiales jugo Brasil (de los 22 hasta 2022)?', '["20", "21", "22", "Todos"]'::jsonb, 3, 'medium', 'stats'),
('Cuantos jugadores aleman fueron campeones en 2014?', '["20", "22", "23", "26"]'::jsonb, 2, 'medium', 'stats'),
('En el Mundial 2022, cuantos equipos eran?', '["24", "32", "36", "48"]'::jsonb, 1, 'easy', 'stats'),
('Cuantos goles convirtio Mbappe en el Mundial 2022?', '["6", "8", "10", "12"]'::jsonb, 1, 'medium', 'stats'),
('Cuantos goles convirtio Messi en el Mundial 2022?', '["5", "6", "7", "8"]'::jsonb, 2, 'medium', 'stats'),
('Cuantos asistencias dio Messi en Mundial 2022?', '["2", "3", "4", "5"]'::jsonb, 1, 'hard', 'stats'),
('Cuantos partidos jugo Argentina en el Mundial 2022?', '["6", "7", "8", "9"]'::jsonb, 1, 'easy', 'stats'),
('Cuanto duro la final del Mundial 2022 (con alargue + penales)?', '["120 min", "135 min", "150 min", "165 min"]'::jsonb, 2, 'medium', 'stats'),
('Cual fue el resultado de la final 2022 antes de penales?', '["2-2", "3-3", "4-3", "3-2"]'::jsonb, 1, 'medium', 'stats'),
('Cuantos penales tuvo la tanda de la final 2022?', '["3", "4", "5", "6"]'::jsonb, 2, 'medium', 'stats'),
('Cuantos goles en propia puerta hubo en el Mundial 2022?', '["0", "2", "4", "6"]'::jsonb, 1, 'hard', 'stats'),
('Cuantos jugadores son seleccionados por pais para un Mundial actual?', '["22", "23", "26", "30"]'::jsonb, 2, 'medium', 'stats'),
('En que Mundial se ampliaron las listas a 26 jugadores?', '["2010", "2014", "2018", "2022"]'::jsonb, 2, 'hard', 'stats'),
('Quien tiene mas finales jugadas como jugador en Mundial?', '["Pele", "Maldini", "Cafu", "Vava"]'::jsonb, 2, 'hard', 'stats'),
('Cafu fue a cuantas finales (jugando)?', '["2", "3", "4", "5"]'::jsonb, 1, 'hard', 'stats'),
('Cuantos arqueros han ganado el Balon de Oro?', '["1", "2", "3", "5"]'::jsonb, 0, 'hard', 'stats'),
('Quien es el unico arquero con Balon de Oro?', '["Buffon", "Casillas", "Yashin", "Banks"]'::jsonb, 2, 'hard', 'stats'),
('En que ano Lev Yashin gano el Balon de Oro?', '["1953", "1963", "1973", "1983"]'::jsonb, 1, 'hard', 'stats'),
('Cuantos jugadores europeos ganaron el Balon de Oro vs sudamericanos en los ultimos 20 anos?', '["~10 europ vs ~10 sudam", "~15 europ vs ~5 sudam", "~5 europ vs ~15 sudam", "Mitad mitad"]'::jsonb, 1, 'hard', 'stats'),
('Quien jugo mas Mundiales por Argentina hasta 2022?', '["Maradona", "Messi", "Batistuta", "Veron"]'::jsonb, 1, 'medium', 'stats'),
('Cuantos Mundiales jugo Messi hasta 2022?', '["3", "4", "5", "6"]'::jsonb, 2, 'easy', 'stats'),
('Cuantos goles hizo Argentina vs Croacia en semis 2022?', '["2", "3", "4", "5"]'::jsonb, 1, 'medium', 'stats'),
('Cuantos partidos consecutivos ganados tiene Italia en algun momento?', '["20", "30", "37", "45"]'::jsonb, 2, 'hard', 'stats'),
('Cual es la mayor goleada en Mundiales?', '["Hungria 10-1 ElSal", "Yugoslavia 9-0 Zaire", "Hungria 9-0 Corea S.", "Brasil 7-1 Alemania"]'::jsonb, 0, 'hard', 'stats'),
('Cuanto duro la racha invicta de Italia (2018-2021)?', '["30", "34", "37", "40"]'::jsonb, 2, 'hard', 'stats'),
('Quien rompio la racha invicta de Italia?', '["Espana", "Inglaterra", "Francia", "Belgica"]'::jsonb, 0, 'hard', 'stats'),
('Cuanto valio Mbappe en su transferencia al PSG (Monaco)?', '["120M", "150M", "180M", "200M"]'::jsonb, 2, 'hard', 'stats'),
('Cuanto valio Neymar al PSG (Barcelona)?', '["180M", "200M", "220M", "222M"]'::jsonb, 3, 'medium', 'stats'),
('Cuantos seguidores tiene Cristiano Ronaldo en Instagram aproximadamente?', '["400M", "500M", "600M", "750M+"]'::jsonb, 3, 'hard', 'stats'),
('En que minuto Messi convirtio su primer gol del Mundial 2022?', '["Min 23 vs Saudi", "Min 35 vs Saudi", "Min 23 vs Mexico", "Min 67 vs Australia"]'::jsonb, 0, 'hard', 'stats'),
('Cuantos paises han ganado al menos 1 Mundial?', '["6", "7", "8", "9"]'::jsonb, 2, 'medium', 'stats'),
('Nombra los paises que ganaron Mundial: Uruguay, Italia, Alemania, Brasil, Inglaterra, Argentina, Francia, Espana. Faltan?', '["Holanda", "Solo esos 8", "Belgica", "Suecia"]'::jsonb, 1, 'hard', 'stats'),
('Cual es el continente con mas Mundiales ganados?', '["Sudamerica", "Europa", "Norteamerica", "Africa"]'::jsonb, 1, 'medium', 'stats'),
('Cuantos Mundiales gano Europa hasta 2022?', '["10", "12", "13", "14"]'::jsonb, 2, 'medium', 'stats'),
('Cuantos Mundiales gano Sudamerica hasta 2022?', '["8", "9", "10", "11"]'::jsonb, 1, 'medium', 'stats'),
('En cuantos Mundiales perdio Argentina la final?', '["2", "3", "4", "5"]'::jsonb, 1, 'medium', 'stats'),
('Cuantas finales jugo Holanda?', '["1", "2", "3", "4"]'::jsonb, 2, 'medium', 'stats'),
('Cuanta gente vio la final del Mundial 2022 (TV global)?', '["500M", "1B", "1.5B+", "2B"]'::jsonb, 2, 'hard', 'stats'),
('Cual ha sido la final con menos goles?', '["0-0 (varios)", "1-0 (varios)", "1-1", "2-0"]'::jsonb, 0, 'hard', 'stats'),

-- ───────────────────────────────────────────────
-- WORLD CUP 2026 (60 preguntas)
-- ───────────────────────────────────────────────
('Donde se juega el Mundial 2026?', '["USA", "USA + Canada", "USA + Canada + Mexico", "Mexico + Argentina"]'::jsonb, 2, 'easy', 'world_cup_2026'),
('Cuantos paises organizan el Mundial 2026?', '["1", "2", "3", "4"]'::jsonb, 2, 'easy', 'world_cup_2026'),
('Cuantos equipos participan del Mundial 2026?', '["32", "40", "48", "64"]'::jsonb, 2, 'easy', 'world_cup_2026'),
('En que mes empieza el Mundial 2026?', '["Mayo", "Junio", "Julio", "Agosto"]'::jsonb, 1, 'easy', 'world_cup_2026'),
('Cuando termina el Mundial 2026 (final)?', '["Junio", "Julio", "Agosto", "Septiembre"]'::jsonb, 1, 'medium', 'world_cup_2026'),
('Donde es la final del Mundial 2026?', '["Los Angeles", "New York/New Jersey", "Mexico DF", "Toronto"]'::jsonb, 1, 'medium', 'world_cup_2026'),
('Cuantos estadios albergan el Mundial 2026?', '["12", "14", "16", "18"]'::jsonb, 2, 'medium', 'world_cup_2026'),
('Cuantos partidos juega el Mundial 2026?', '["64", "80", "104", "128"]'::jsonb, 2, 'medium', 'world_cup_2026'),
('Como se distribuyen los grupos del Mundial 2026?', '["6 grupos de 8", "8 grupos de 6", "12 grupos de 4", "16 grupos de 3"]'::jsonb, 2, 'medium', 'world_cup_2026'),
('Cuantos pasan a 16vos por grupo del Mundial 2026?', '["1", "2", "Todos", "3 (top 2 + mejores 3ros)"]'::jsonb, 3, 'hard', 'world_cup_2026'),
('Cuantos cupos tiene Sudamerica para el Mundial 2026?', '["4", "5", "6", "6+repechaje"]'::jsonb, 3, 'medium', 'world_cup_2026'),
('Cuantos cupos tiene Europa para el Mundial 2026?', '["13", "14", "16", "18"]'::jsonb, 2, 'medium', 'world_cup_2026'),
('Cuantos cupos tiene Africa para el Mundial 2026?', '["5", "7", "9", "11"]'::jsonb, 2, 'medium', 'world_cup_2026'),
('Cuantos cupos tiene Asia para el Mundial 2026?', '["4", "6", "8", "10"]'::jsonb, 2, 'medium', 'world_cup_2026'),
('Cuantos cupos tiene Concacaf para el Mundial 2026?', '["3", "4", "6 (incl. anfitriones)", "8"]'::jsonb, 2, 'medium', 'world_cup_2026'),
('Cuantos cupos tiene Oceania para el Mundial 2026?', '["0", "1", "2", "3"]'::jsonb, 1, 'medium', 'world_cup_2026'),
('Cual fue el primer Mundial con 32 equipos?', '["1990", "1994", "1998", "2002"]'::jsonb, 2, 'medium', 'world_cup_2026'),
('Esta es la primera vez con 48 equipos?', '["Si", "No, ya fue 2022", "No, ya fue 2018", "No, fue 2014"]'::jsonb, 0, 'easy', 'world_cup_2026'),
('Cual fue el ultimo Mundial en Norteamerica antes de 2026?', '["1986 Mexico", "1994 USA", "Ambos", "Ninguno"]'::jsonb, 2, 'medium', 'world_cup_2026'),
('Cual fue el primer Mundial en Estados Unidos?', '["1986", "1990", "1994", "1998"]'::jsonb, 2, 'medium', 'world_cup_2026'),
('Que Mundial dio inicio a la era de 48 equipos?', '["2018", "2022", "2026", "2030"]'::jsonb, 2, 'easy', 'world_cup_2026'),
('Como se clasifica Argentina al Mundial 2026?', '["Eliminatoria sudamericana", "Repechaje", "Por ranking", "Como invitado"]'::jsonb, 0, 'easy', 'world_cup_2026'),
('Argentina es la actual campeona, pero juega eliminatorias?', '["Si", "No, esta clasificado por ser campeon", "Solo si quiere", "No, juega como invitado"]'::jsonb, 0, 'medium', 'world_cup_2026'),
('Mexico se clasifica al Mundial 2026?', '["Por anfitrion", "Por eliminatoria", "Por ranking", "Por invitacion"]'::jsonb, 0, 'easy', 'world_cup_2026'),
('USA se clasifica al Mundial 2026?', '["Por anfitrion", "Por eliminatoria", "Por ranking", "Por invitacion"]'::jsonb, 0, 'easy', 'world_cup_2026'),
('Canada se clasifica al Mundial 2026?', '["Por anfitrion", "Por eliminatoria", "Por ranking", "Por invitacion"]'::jsonb, 0, 'easy', 'world_cup_2026'),
('Cual fue el primer Mundial de Canada (antes de 2026)?', '["No habia jugado", "1990", "1986", "2022"]'::jsonb, 2, 'medium', 'world_cup_2026'),
('En que estadio mexicano se juega el Mundial 2026?', '["Azteca", "Akron", "Estadio BBVA", "Todos los anteriores"]'::jsonb, 3, 'hard', 'world_cup_2026'),
('Que estadio en Mexico DF se renombro para el Mundial 2026?', '["Estadio Azteca", "Estadio Banorte", "Estadio Olimpico", "Estadio Cuauhtemoc"]'::jsonb, 1, 'hard', 'world_cup_2026'),
('Cual sera el partido inaugural del Mundial 2026?', '["Mexico vs ?", "Argentina vs ?", "USA vs Canada", "Sera definido"]'::jsonb, 0, 'medium', 'world_cup_2026'),
('Donde es el partido inaugural?', '["Estadio Banorte (Mexico)", "MetLife (NJ)", "BMO Field (Toronto)", "Rose Bowl (LA)"]'::jsonb, 0, 'hard', 'world_cup_2026'),
('Cuantos estadios USA tiene para el Mundial 2026?', '["8", "10", "11", "13"]'::jsonb, 2, 'hard', 'world_cup_2026'),
('Cuantos estadios Canada tiene?', '["1", "2", "3", "4"]'::jsonb, 1, 'hard', 'world_cup_2026'),
('Cuantos estadios Mexico tiene?', '["2", "3", "4", "5"]'::jsonb, 1, 'hard', 'world_cup_2026'),
('En que ciudad de USA se juega la final del Mundial 2026?', '["Los Angeles", "Nueva York/NJ", "Miami", "Dallas"]'::jsonb, 1, 'medium', 'world_cup_2026'),
('Como se llama el estadio donde es la final 2026?', '["SoFi Stadium", "MetLife Stadium", "AT&T Stadium", "Mercedes Benz"]'::jsonb, 1, 'hard', 'world_cup_2026'),
('Donde es el partido inaugural en Mexico?', '["Mexico DF", "Guadalajara", "Monterrey", "Por definir"]'::jsonb, 0, 'medium', 'world_cup_2026'),
('Como se llama la mascota del Mundial 2026?', '["Maple, Zayu, Clutch", "Por anunciar", "Mateo", "Solo USA tiene mascota"]'::jsonb, 0, 'hard', 'world_cup_2026'),
('Quien dio el sorteo de grupos del Mundial 2026?', '["FIFA en Washington", "FIFA en Mexico", "FIFA en Las Vegas", "FIFA en Miami"]'::jsonb, 0, 'hard', 'world_cup_2026'),
('Cuando se hizo el sorteo del Mundial 2026?', '["Octubre 2025", "Diciembre 2025", "Enero 2026", "Marzo 2026"]'::jsonb, 1, 'hard', 'world_cup_2026'),
('En que grupo cayo Argentina para Mundial 2026?', '["Grupo A", "Grupo D", "Grupo G", "Por anunciar"]'::jsonb, 0, 'hard', 'world_cup_2026'),
('Quienes son rivales de Argentina en grupo 2026?', '["South Korea, Czech Republic, South Africa", "Brazil, Spain, Iran", "France, Egypt, Korea", "Por anunciar"]'::jsonb, 0, 'hard', 'world_cup_2026'),
('Cuantas selecciones europeas estaran en el Mundial 2026?', '["13", "14", "15", "16"]'::jsonb, 1, 'medium', 'world_cup_2026'),
('Cuantas naciones africanas estaran en el Mundial 2026?', '["5", "7", "9", "11"]'::jsonb, 2, 'medium', 'world_cup_2026'),
('Argentina viaja con cuantos jugadores al Mundial 2026?', '["23", "24", "26", "28"]'::jsonb, 2, 'medium', 'world_cup_2026'),
('Quien es la actual campeona del mundo (jugando 2026)?', '["Brasil", "Francia", "Argentina", "Espana"]'::jsonb, 2, 'easy', 'world_cup_2026'),
('Cuantos goles necesita Messi en 2026 para empatar a Klose como goleador?', '["1", "2", "3", "Ya lo paso"]'::jsonb, 2, 'hard', 'world_cup_2026'),
('Klose tiene cuantos goles en Mundiales?', '["13", "14", "15", "16"]'::jsonb, 3, 'medium', 'world_cup_2026'),
('Edad de Messi al Mundial 2026?', '["37", "38", "39", "40"]'::jsonb, 2, 'medium', 'world_cup_2026'),
('Edad de Cristiano al Mundial 2026?', '["40", "41", "42", "43"]'::jsonb, 1, 'medium', 'world_cup_2026'),
('Edad de Mbappe al Mundial 2026?', '["26", "27", "28", "29"]'::jsonb, 1, 'medium', 'world_cup_2026'),
('Edad de Haaland al Mundial 2026 (si Noruega clasifica)?', '["25", "26", "27", "28"]'::jsonb, 0, 'hard', 'world_cup_2026'),
('Marca oficial de la pelota del Mundial 2026?', '["Adidas", "Nike", "Puma", "Por definir"]'::jsonb, 0, 'easy', 'world_cup_2026'),
('Quien sera el patrocinador principal del Mundial 2026 segun FIFA?', '["Visa", "Coca-Cola", "Adidas", "Multiples"]'::jsonb, 3, 'hard', 'world_cup_2026'),
('En cuantos husos horarios se juega el Mundial 2026?', '["1", "3", "4", "5"]'::jsonb, 3, 'hard', 'world_cup_2026'),
('Cuantos dias dura el Mundial 2026 aprox?', '["20", "30", "39", "45"]'::jsonb, 2, 'medium', 'world_cup_2026'),
('El estadio Azteca tiene capacidad para cuanta gente?', '["60k", "70k", "87k", "100k"]'::jsonb, 2, 'medium', 'world_cup_2026'),
('El MetLife Stadium tiene capacidad para cuanta gente?', '["60k", "70k", "82k", "100k"]'::jsonb, 2, 'hard', 'world_cup_2026'),
('Cual es el primer Mundial con 3 paises anfitriones?', '["2002", "2018", "2026", "2030"]'::jsonb, 2, 'medium', 'world_cup_2026'),
('Cual sera la lengua oficial del Mundial 2026?', '["Solo ingles", "Solo espanol", "Ingles, espanol, frances", "Sin oficial"]'::jsonb, 2, 'hard', 'world_cup_2026'),

-- ───────────────────────────────────────────────
-- GENERAL (60 preguntas)
-- ───────────────────────────────────────────────
('Que se grita cuando entra la pelota en el arco?', '["Centro", "Gol", "Penal", "Tiro"]'::jsonb, 1, 'easy', 'general'),
('Como se llama el partido entre River y Boca?', '["El Clasico", "Superclasico", "Derbi nacional", "Madre de todas las batallas"]'::jsonb, 1, 'easy', 'general'),
('Donde es el "El Clasico" entre Real Madrid y Barcelona?', '["Madrid", "Barcelona", "Ambas ciudades", "Sevilla"]'::jsonb, 2, 'easy', 'general'),
('Como se llama el clasico ingles entre Liverpool y Man United?', '["North-West derby", "Premier derby", "Red derby", "British classic"]'::jsonb, 0, 'medium', 'general'),
('Como se llama el clasico ingles entre Arsenal y Tottenham?', '["North London Derby", "South London Derby", "Premier Derby", "Cup Derby"]'::jsonb, 0, 'medium', 'general'),
('Como se llama la final continental europea?', '["Champions League final", "UEFA Cup", "Super Cup", "Europa Final"]'::jsonb, 0, 'easy', 'general'),
('Quien gano la Champions 2024?', '["Real Madrid", "Manchester City", "PSG", "Bayern"]'::jsonb, 0, 'easy', 'general'),
('Quien gano la Champions 2023?', '["Real Madrid", "Manchester City", "Liverpool", "Chelsea"]'::jsonb, 1, 'easy', 'general'),
('Cuantas Champions ganó el Real Madrid hasta 2024?', '["12", "13", "14", "15"]'::jsonb, 3, 'medium', 'general'),
('Quien es el rey de Champions con mas titulos?', '["Real Madrid", "Barcelona", "Milan", "Liverpool"]'::jsonb, 0, 'easy', 'general'),
('Que es la Conmebol?', '["Confederacion sudamericana", "Confederacion europea", "Confederacion africana", "Liga sudamericana"]'::jsonb, 0, 'medium', 'general'),
('Que es la UEFA?', '["Confederacion europea", "Liga inglesa", "Comite olimpico", "Asociacion mundial"]'::jsonb, 0, 'easy', 'general'),
('Donde tiene su sede la FIFA?', '["Paris", "Londres", "Zurich", "New York"]'::jsonb, 2, 'medium', 'general'),
('Que es la Copa America?', '["Torneo sudamericano", "Torneo USA", "Torneo Concacaf", "Torneo Centroamericano"]'::jsonb, 0, 'easy', 'general'),
('Quien gano la Copa America 2024?', '["Argentina", "Brasil", "Colombia", "Uruguay"]'::jsonb, 0, 'easy', 'general'),
('Que es la Eurocopa?', '["Liga europea", "Torneo de selecciones europeas cada 4 anos", "Champions League", "UEFA Nations League"]'::jsonb, 1, 'easy', 'general'),
('Quien gano la Eurocopa 2024?', '["Inglaterra", "Espana", "Francia", "Alemania"]'::jsonb, 1, 'easy', 'general'),
('Que liga inglesa es la Premier League?', '["Segunda division", "Primera division", "Copa", "Champions"]'::jsonb, 1, 'easy', 'general'),
('Que liga es La Liga?', '["Francia", "Italia", "Espana", "Alemania"]'::jsonb, 2, 'easy', 'general'),
('Que liga es la Bundesliga?', '["Alemania", "Austria", "Suiza", "Holanda"]'::jsonb, 0, 'easy', 'general'),
('Que liga es la Ligue 1?', '["Belgica", "Suiza", "Francia", "Holanda"]'::jsonb, 2, 'easy', 'general'),
('Que liga es la Eredivisie?', '["Alemania", "Holanda", "Belgica", "Dinamarca"]'::jsonb, 1, 'medium', 'general'),
('Donde juega el Boca Juniors?', '["River Plate", "La Bombonera", "Estadio Monumental", "La Plata"]'::jsonb, 1, 'easy', 'general'),
('Donde juega River Plate?', '["La Bombonera", "Estadio Monumental", "Velez", "San Lorenzo"]'::jsonb, 1, 'easy', 'general'),
('Como se llaman los partidos clasicos entre Mexico y USA en futbol?', '["El derby norte", "Concacaf classic", "Dos a Cero", "Border derby"]'::jsonb, 2, 'hard', 'general'),
('El sorteo del Mundial usa que tecnologia?', '["Bolas aleatorias", "Sorteo digital", "Algoritmo", "Globo loto"]'::jsonb, 0, 'medium', 'general'),
('Que es el Pichichi?', '["Premio al goleador de La Liga", "Premio al asistidor", "Trofeo de mejor portero", "Premio al fair play"]'::jsonb, 0, 'medium', 'general'),
('Que premio gana el goleador en Inglaterra?', '["Pichichi", "Premier League Golden Boot", "Bota de Oro", "Boot Award"]'::jsonb, 1, 'medium', 'general'),
('Quien gano el Pichichi 2024?', '["Lewandowski", "Vinicius", "Bellingham", "Lamine Yamal"]'::jsonb, 0, 'hard', 'general'),
('Que es el Camp Nou?', '["Estadio del Atletico", "Estadio del Real Madrid", "Estadio del Barcelona", "Estadio de Sevilla"]'::jsonb, 2, 'easy', 'general'),
('Que es Anfield?', '["Estadio del Liverpool", "Estadio del Manchester", "Estadio de Chelsea", "Estadio de Arsenal"]'::jsonb, 0, 'easy', 'general'),
('Como se llama el estadio del Manchester City?', '["Old Trafford", "Etihad Stadium", "Anfield", "Stamford Bridge"]'::jsonb, 1, 'medium', 'general'),
('Como se llama el estadio del Bayern Munich?', '["Allianz Arena", "Signal Iduna Park", "Olympiastadion", "Veltins Arena"]'::jsonb, 0, 'medium', 'general'),
('Donde juega Cristiano Ronaldo en 2024-2025?', '["Manchester United", "Real Madrid", "Al-Nassr (Arabia)", "PSG"]'::jsonb, 2, 'easy', 'general'),
('Donde juega Messi en 2024-2025?', '["Barcelona", "PSG", "Inter Miami", "Newells"]'::jsonb, 2, 'easy', 'general'),
('Donde juega Neymar?', '["Barcelona", "PSG", "Al-Hilal", "Santos"]'::jsonb, 2, 'medium', 'general'),
('Donde juega Mbappe en 2024-2025?', '["PSG", "Real Madrid", "Barcelona", "Manchester City"]'::jsonb, 1, 'easy', 'general'),
('Donde juega Erling Haaland?', '["Manchester City", "Borussia", "Bayern", "Real Madrid"]'::jsonb, 0, 'easy', 'general'),
('Donde juega Vinicius Jr?', '["Real Madrid", "Barcelona", "PSG", "Santos"]'::jsonb, 0, 'easy', 'general'),
('Donde juega Bellingham?', '["Real Madrid", "Manchester", "Liverpool", "Borussia"]'::jsonb, 0, 'easy', 'general'),
('Que es el "Aurinegro" en Brasil?', '["Apodo de Pele", "Apodo de Brasil", "Apodo de Botafogo (negro/oro)", "Apodo del Maracana"]'::jsonb, 2, 'hard', 'general'),
('Que es la "Verdeamarela"?', '["Argentina", "Brasil", "Mexico", "Portugal"]'::jsonb, 1, 'medium', 'general'),
('Apodo de la seleccion argentina?', '["La Albiceleste", "La Verdeamarela", "Los Diablos", "La Roja"]'::jsonb, 0, 'easy', 'general'),
('Apodo de la seleccion espanola?', '["La Roja", "La Furia Roja", "Los Toros", "Espana FC"]'::jsonb, 0, 'easy', 'general'),
('Apodo de la seleccion italiana?', '["La Azzurra", "Italia", "Los Romanos", "El Calcio"]'::jsonb, 0, 'medium', 'general'),
('Apodo de la seleccion alemana?', '["Die Mannschaft", "Los Panzers", "La Maquina", "Bavarianos"]'::jsonb, 0, 'medium', 'general'),
('Apodo de la seleccion francesa?', '["Les Bleus", "La Tricolor", "Los Galos", "Los Mosqueteros"]'::jsonb, 0, 'medium', 'general'),
('Apodo de la seleccion inglesa?', '["The Three Lions", "Los Britanicos", "The Red Devils", "Los Reales"]'::jsonb, 0, 'medium', 'general'),
('Apodo de la seleccion holandesa?', '["Los Tulipanes", "Los Naranjas", "La Naranja Mecanica", "Oranje"]'::jsonb, 3, 'medium', 'general'),
('Apodo de la seleccion portuguesa?', '["Los Lusos", "A Selecao das Quinas", "La Roja", "Los Navegantes"]'::jsonb, 1, 'hard', 'general'),
('Apodo de la seleccion uruguaya?', '["La Garra Charrua", "Los Celestes", "La Banda Oriental", "Todos los anteriores"]'::jsonb, 3, 'hard', 'general'),
('Que es la Eurocopa femenina?', '["Eurocopa femenina UEFA", "Mundial femenino", "Champions femenina", "Copa America femenina"]'::jsonb, 0, 'hard', 'general'),
('Quien gano la Eurocopa femenina 2025?', '["Inglaterra", "Espana", "Alemania", "Francia"]'::jsonb, 1, 'hard', 'general'),
('Cual fue el primer Mundial femenino?', '["1991", "1995", "1999", "2003"]'::jsonb, 0, 'hard', 'general'),
('Quien gano el Mundial femenino 2023?', '["USA", "Espana", "Inglaterra", "Suecia"]'::jsonb, 1, 'medium', 'general'),
('Donde se jugo el Mundial femenino 2023?', '["USA", "Inglaterra", "Australia/NZ", "Francia"]'::jsonb, 2, 'hard', 'general'),
('Que es el FIFA The Best?', '["Premio al mejor jugador del ano", "Trofeo del Mundial", "Premio al fair play", "Premio al mejor club"]'::jsonb, 0, 'medium', 'general'),
('Quien gano FIFA The Best 2023?', '["Messi", "Mbappe", "Haaland", "Bellingham"]'::jsonb, 0, 'medium', 'general'),
('Quien fundo la FIFA?', '["Jules Rimet", "Joao Havelange", "Sepp Blatter", "Joseph Bonnet"]'::jsonb, 3, 'hard', 'general');

\echo ''
\echo '=== Counts post-insert ==='
SELECT difficulty, COUNT(*) FROM trivia_questions GROUP BY difficulty ORDER BY difficulty;
SELECT category, COUNT(*) FROM trivia_questions GROUP BY category ORDER BY category;
SELECT COUNT(*) AS total FROM trivia_questions;

COMMIT;
